### PR TITLE
authorization_roles.capabilities is unordered

### LINKED ISSUE #95: authorization_role capabilities should be a Set (unordered)
Due to the way capabilities are stored in the underlying `authorize.conf` file, they are inherently unordered, and the order returned by `splunkd` via the REST API is not determined by the order they were created (even when created by the same REST API). This results in non-empty plans for the same configuration after apply.

This can be seen by [reordering the list of capabilities](https://github.com/splunk/terraform-provider-splunk/commit/bc525ff00243d26bfa18bb9d5c1d2705acad074b) passed in the test, which results in this failed acceptance test:

```
=== RUN   TestAccSplunkAuthorizationRoles
    testing.go:684: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: splunk_authorization_roles.role
          capabilities.#:                        "2" => "2"
          capabilities.0:                        "accelerate_datamodel" => "change_authentication"
          capabilities.1:                        "change_authentication" => "accelerate_datamodel"
          cumulative_realtime_search_jobs_quota: "0" => "0"
          cumulative_search_jobs_quota:          "0" => "0"
          default_app:                           "search" => "search"
          id:                                    "new-role" => "new-role"
          imported_roles.#:                      "1" => "1"
          imported_roles.0:                      "user" => "user"
          name:                                  "new-role" => "new-role"
          realtime_search_jobs_quota:            "6" => "6"
          search_disk_quota:                     "100" => "100"
          search_filter:                         "" => ""
          search_indexes_allowed.#:              "2" => "2"
          search_indexes_allowed.0:              "_audit" => "_audit"
          search_indexes_allowed.1:              "_internal" => "_internal"
          search_indexes_default.#:              "2" => "2"
          search_indexes_default.0:              "_audit" => "_audit"
          search_indexes_default.1:              "_internal" => "_internal"
          search_jobs_quota:                     "3" => "3"
          search_time_win:                       "-1" => "-1"
        
        
        
        STATE:
        
        splunk_authorization_roles.role:
          ID = new-role
          provider = provider.splunk
          capabilities.# = 2
          capabilities.0 = accelerate_datamodel
          capabilities.1 = change_authentication
          cumulative_realtime_search_jobs_quota = 0
          cumulative_search_jobs_quota = 0
          default_app = search
          imported_roles.# = 1
          imported_roles.0 = user
          name = new-role
          realtime_search_jobs_quota = 6
          search_disk_quota = 100
          search_filter = 
          search_indexes_allowed.# = 2
          search_indexes_allowed.0 = _audit
          search_indexes_allowed.1 = _internal
          search_indexes_default.# = 2
          search_indexes_default.0 = _audit
          search_indexes_default.1 = _internal
          search_jobs_quota = 3
          search_time_win = -1
--- FAIL: TestAccSplunkAuthorizationRoles (0.15s)
FAIL
FAIL    github.com/splunk/terraform-provider-splunk/splunk      0.629s
FAIL
```

### PR DESCRIPTION
**Pull request by micahkemp-splunk**
Closes #95

This PR makes the `capabilities` argument of `splunk_authorization_roles` an unordered Set instead of an ordered List.

This allows arbitrary ordering of the configuration without needing to know how Splunk's API will order the capabilities when it returns them.

### CODE REVIEW

File: splunk/resource_splunk_authorization_roles_test.go [hunk 1]
```diff
@@ -47,8 +49,6 @@ func TestAccSplunkAuthorizationRoles(t *testing.T) {
 					resource.TestCheckResourceAttr(resourceName, "imported_roles.#", "1"),
 					resource.TestCheckResourceAttr(resourceName, "imported_roles.0", "user"),
 					resource.TestCheckResourceAttr(resourceName, "capabilities.#", "2"),
-					resource.TestCheckResourceAttr(resourceName, "capabilities.0", "accelerate_datamodel"),
-					resource.TestCheckResourceAttr(resourceName, "capabilities.1", "change_authentication"),
```
Comment (micahkemp-splunk) [inline splunk/resource_splunk_authorization_roles_test.go:51]: It's not (easily) possible to test the values of a `TypeSet` field, so this had to be removed.

Terraform's test framework effectively tests it for you, however, since it applies the configuration and checks for a non-empty plan afterwards.  So as long as `capabilities` are defined in the configuration being tested, there is implicit testing of the values of the `capabilities` stored in state.

File: splunk/resource_splunk_authorization_roles_test.go [hunk 2]
```diff
@@ -13,7 +13,8 @@ resource "splunk_authorization_roles" "role" {
   name = "new-role"
   default_app = "search"
   imported_roles = ["user"]
-  capabilities = ["accelerate_datamodel", "change_authentication"]
+  # capabilities are explicitly listed in a different order than returned by the Splunk API
+  capabilities = ["change_authentication", "accelerate_datamodel"]
```
Comment (micahkemp-splunk) [inline splunk/resource_splunk_authorization_roles_test.go:17]: This change, without the change to using `TypeSet`, results in this failed acceptance test:

```
=== RUN   TestAccSplunkAuthorizationRoles
    testing.go:684: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        UPDATE: splunk_authorization_roles.role
          capabilities.#:                        "2" => "2"
          capabilities.0:                        "accelerate_datamodel" => "change_authentication"
          capabilities.1:                        "change_authentication" => "accelerate_datamodel"
          cumulative_realtime_search_jobs_quota: "0" => "0"
          cumulative_search_jobs_quota:          "0" => "0"
          default_app:                           "search" => "search"
          id:                                    "new-role" => "new-role"
          imported_roles.#:                      "1" => "1"
          imported_roles.0:                      "user" => "user"
          name:                                  "new-role" => "new-role"
          realtime_search_jobs_quota:            "6" => "6"
          search_disk_quota:                     "100" => "100"
          search_filter:                         "" => ""
          search_indexes_allowed.#:              "2" => "2"
          search_indexes_allowed.0:              "_audit" => "_audit"
          search_indexes_allowed.1:              "_internal" => "_internal"
          search_indexes_default.#:              "2" => "2"
          search_indexes_default.0:              "_audit" => "_audit"
          search_indexes_default.1:              "_internal" => "_internal"
          search_jobs_quota:                     "3" => "3"
          search_time_win:                       "-1" => "-1"
        
        
        
        STATE:
        
        splunk_authorization_roles.role:
          ID = new-role
          provider = provider.splunk
          capabilities.# = 2
          capabilities.0 = accelerate_datamodel
          capabilities.1 = change_authentication
          cumulative_realtime_search_jobs_quota = 0
          cumulative_search_jobs_quota = 0
          default_app = search
          imported_roles.# = 1
          imported_roles.0 = user
          name = new-role
          realtime_search_jobs_quota = 6
          search_disk_quota = 100
          search_filter = 
          search_indexes_allowed.# = 2
          search_indexes_allowed.0 = _audit
          search_indexes_allowed.1 = _internal
          search_indexes_default.# = 2
          search_indexes_default.0 = _audit
          search_indexes_default.1 = _internal
          search_jobs_quota = 3
          search_time_win = -1
--- FAIL: TestAccSplunkAuthorizationRoles (0.15s)
FAIL
FAIL    github.com/splunk/terraform-provider-splunk/splunk      0.629s
FAIL
```

**Review by anelson-splunk — APPROVED** [review]
