### PR TITLE
#105 splunk_data_ui_views - Don't read all views

### LINKED ISSUE #105: Error on Terraform provider while creating Knowledge objects
I try to create KOs (Dashboard/Saved search) on Splunk cloud and it successfully created the object on the splunk stack, but when it try to confirm, it gets error outs, as we have 1000s of KOs, I suspect its getting the time out after 1m when queries the endpoint. Note: I do set timeout as 600 on the provider connection..

Code:
```terraform
terraform {
  required_providers {
    splunk = {
      source  = "splunk/splunk"
    }
  }
}

provider "splunk" {
  url           = "xyz.splunkcloud.com:8089"
  auth_token    = "<jwt_token>"
  insecure_skip_verify = true
  timeout = 600
}

resource "splunk_data_ui_views" "terraform_operations" {
  name     = "Terraform"
  eai_data = "<dashboard><label>Terraform</label><description>Terraform operations</description><row><panel><chart><search><query>index=_internal sourcetype=splunkd_access useragent=\"splunk-simple-go-client\" | timechart fixedrange=f values(status) by uri_path</query><earliest>-24h@h</earliest><latest>now</latest><sampleRatio>1</sampleRatio></search><option name=\"charting.axisLabelsX.majorLabelStyle.overflowMode\">ellipsisNone</option><option name=\"charting.axisLabelsX.majorLabelStyle.rotation\">0</option><option name=\"charting.axisTitleX.visibility\">collapsed</option><option name=\"charting.axisTitleY.text\">HTTP status codes</option><option name=\"charting.axisTitleY.visibility\">visible</option><option name=\"charting.axisTitleY2.visibility\">visible</option><option name=\"charting.axisX.abbreviation\">none</option><option name=\"charting.axisX.scale\">linear</option><option name=\"charting.axisY.abbreviation\">none</option><option name=\"charting.axisY.scale\">linear</option><option name=\"charting.axisY2.abbreviation\">none</option><option name=\"charting.axisY2.enabled\">0</option><option name=\"charting.axisY2.scale\">inherit</option><option name=\"charting.chart\">column</option><option name=\"charting.chart.bubbleMaximumSize\">50</option><option name=\"charting.chart.bubbleMinimumSize\">10</option><option name=\"charting.chart.bubbleSizeBy\">area</option><option name=\"charting.chart.nullValueMode\">connect</option><option name=\"charting.chart.showDataLabels\">none</option><option name=\"charting.chart.sliceCollapsingThreshold\">0.01</option><option name=\"charting.chart.stackMode\">default</option><option name=\"charting.chart.style\">shiny</option><option name=\"charting.drilldown\">none</option><option name=\"charting.layout.splitSeries\">0</option><option name=\"charting.layout.splitSeries.allowIndependentYRanges\">0</option><option name=\"charting.legend.labelStyle.overflowMode\">ellipsisMiddle</option><option name=\"charting.legend.mode\">standard</option><option name=\"charting.legend.placement\">right</option><option name=\"charting.lineWidth\">2</option><option name=\"trellis.enabled\">0</option><option name=\"trellis.scales.shared\">1</option><option name=\"trellis.size\">small</option><option name=\"trellis.splitBy\">_aggregation</option></chart></panel></row></dashboard>"
  acl {
    app     = "ops"
    owner   = "abc"
    sharing = "global"
  }
}

resource "splunk_saved_searches" "terraform-search-01" {
  actions                   = "email"
  action_email_format       = "table"
  action_email_max_time     = "5m"
  action_email_send_results = true
  action_email_subject      = "Splunk Alert: $name$"
  action_email_to           = "abc@xyz.com"
  action_email_track_alert  = true
  alert_comparator          = "greater than"
  alert_digest_mode         = true
  alert_expires             = "30d"
  alert_threshold           = "0"
  alert_type                = "number of events"
  description               = "Terraform activities alerts"
  dispatch_earliest_time    = "-15m@m"
  dispatch_latest_time      = "-1m@m"
  cron_schedule             = "*/15 * * * *"
  name                      = "terraform-search-01"
  schedule_priority         = "default"
  search                    = "index=_internal sourcetype=splunkd_access useragent=splunk-simple-go-client"

  acl {
    app     = "ops"
    owner   = "abc"
    sharing = "app"
  }
}
```

To perform exactly these actions, run the following command to apply:
    `terraform apply "splunk1.tf.plan"`
```console
sh-3.2$ terraform apply "splunk1.tf.plan"
splunk_data_ui_views.terraform_operations: Creating...
splunk_saved_searches.terraform-search-01: Creating...
splunk_saved_searches.terraform-search-01: Still creating... [10s elapsed]
splunk_data_ui_views.terraform_operations: Still creating... [10s elapsed]
splunk_saved_searches.terraform-search-01: Still creating... [20s elapsed]
splunk_data_ui_views.terraform_operations: Still creating... [20s elapsed]
splunk_data_ui_views.terraform_operations: Still creating... [30s elapsed]
splunk_saved_searches.terraform-search-01: Still creating... [30s elapsed]
splunk_saved_searches.terraform-search-01: Still creating... [40s elapsed]
splunk_data_ui_views.terraform_operations: Still creating... [40s elapsed]
splunk_saved_searches.terraform-search-01: Still creating... [50s elapsed]
splunk_data_ui_views.terraform_operations: Still creating... [50s elapsed]
splunk_saved_searches.terraform-search-01: Still creating... [1m0s elapsed]
splunk_data_ui_views.terraform_operations: Still creating... [1m0s elapsed]
splunk_saved_searches.terraform-search-01: Still creating... [1m10s elapsed]

Error: Get "https://xyz.splunkcloud.com:8089/servicesNS/-/-/data/ui/views?count=-1&output_mode=json": EOF
│ 
│   with splunk_data_ui_views.terraform_operations,
│   on main.tf line 25, in resource "splunk_data_ui_views" "terraform_operations":
│   25: resource "splunk_data_ui_views" "terraform_operations" {
│ 
╵
╷
│ Error: Get "https://xyz.splunkcloud.com:8089/servicesNS/-/-/saved/searches?count=-1&output_mode=json": EOF
│ 
│   with splunk_saved_searches.terraform-search-01,
│   on main.tf line 35, in resource "splunk_saved_searches" "terraform-search-01":
│   35: resource "splunk_saved_searches" "terraform-search-01" {
│ 
```

### PR DESCRIPTION
**Pull request by micahkemp-splunk**
Closes #105 

This PR attempts to improve the performance of the `splunk_data_ui_views` resource during the read phase.

The current implementation first reads all views (`servicesNS/-/-/data/ui/views`) and iterates through the found views for the first view with a name matching the resource's name. This method is flawed for two major reasons:

* Asking for all views in all namespaces is likely to return a very large number of results, and the request itself is likely to take a long time to complete.
* The list of returned views may very well contain multiple views with the same name as the resource. Without also matching the namespace (app/user), there's a non-negligible chance that the wrong view would be the one returned.

These issues are addressed in this pull request by:

* No longer reading all dashboard objects
* Using the found or pseudo-default ACL configuration for all actions (create, read, update, delete).

Output from related acceptance tests:

```
TF_ACC=1 <redacted> go test ./... -timeout 30s -run TestAccSplunkDashboards -v        
...
=== RUN   TestAccSplunkDashboards
--- PASS: TestAccSplunkDashboards (0.26s)
=== RUN   TestAccSplunkDashboardsWithAcl
--- PASS: TestAccSplunkDashboardsWithAcl (0.25s)
PASS
ok      github.com/splunk/terraform-provider-splunk/splunk      0.919s
```

### CODE REVIEW

File: client/data_ui_views.go [hunk 1]
```diff
@@ -59,13 +59,3 @@ func (client *Client) DeleteDashboardObject(owner string, app string, name strin
...
-
-func (client *Client) ReadAllDashboardObject() (*http.Response, error) {
-	endpoint := client.BuildSplunkURL(nil, "servicesNS", "-", "-", "data", "ui", "views")
-	resp, err := client.Get(endpoint)
-	if err != nil {
-		return nil, err
-	}
-
-	return resp, nil
-}
```
Comment (micahkemp-splunk) [inline client/data_ui_views.go:71]: This method is no longer used, so it was removed.

File: splunk/resource_splunk_data_ui_views.go [hunk 2]
```diff
@@ -43,24 +43,15 @@ func splunkDashboardsCreate(d *schema.ResourceData, meta interface{}) error {
...
 		return err
 	}
 
-	if _, ok := d.GetOk("acl"); ok {
-		err = (*provider.Client).UpdateAcl(aclObject.Owner, aclObject.App, name, aclObject, "data", "ui", "views")
-		if err != nil {
-			return err
-		}
+	if err := (*provider.Client).UpdateAcl(aclObject.Owner, aclObject.App, name, aclObject, "data", "ui", "views"); err != nil {
+		return err
```
Comment (micahkemp-splunk) [inline splunk/resource_splunk_data_ui_views.go:54]: Since I had to make a change to these lines I also changed it to scope `err` to the `if` block.

File: splunk/resource_splunk_data_ui_views.go [hunk 3]
```diff
@@ -120,25 +99,14 @@ func splunkDashboardsUpdate(d *schema.ResourceData, meta interface{}) error {
...
-	} else {
-		aclObject.App = "search"
-		aclObject.Owner = "admin"
-		aclObject.Sharing = "user"
-	}
-	err := (*provider.Client).UpdateDashboardObject(aclObject.Owner, aclObject.App, name, splunkDashboardsObj)
-	if err != nil {
+	aclObject := getResourceDataViewACL(d)
+
+	if err := (*provider.Client).UpdateDashboardObject(aclObject.Owner, aclObject.App, name, splunkDashboardsObj); err != nil {
```
Comment (micahkemp-splunk) [inline splunk/resource_splunk_data_ui_views.go:104]: Since I had to make a change to these lines I also changed it to scope err to the if block.

File: splunk/resource_splunk_data_ui_views.go [hunk 4]
```diff
@@ -120,25 +99,14 @@ func splunkDashboardsUpdate(d *schema.ResourceData, meta interface{}) error {
...
 	}
 
-	//ACL update
-	if _, ok := d.GetOk("acl"); ok {
-		err = (*provider.Client).UpdateAcl(aclObject.Owner, aclObject.App, name, aclObject, "data", "ui", "views")
-		if err != nil {
-			return err
-		}
+	if err := (*provider.Client).UpdateAcl(aclObject.Owner, aclObject.App, name, aclObject, "data", "ui", "views"); err != nil {
+		return err
```
Comment (micahkemp-splunk) [inline splunk/resource_splunk_data_ui_views.go:109]: Since I had to make a change to these lines I also changed it to scope err to the if block.

**Review by rfrey-splunk — APPROVED** [review]
